### ISSUE TITLE
Could not get unknown property issue

### ISSUE THREAD

**Issue by SimonBerry555** [mygrocerydeals/gradle-s3-plugin#1]
Hi,
I have followed the README to add the plugin.

```groovy
plugins {
	id "java"
	id "maven"
	id "maven-publish"
	id 'org.springframework.boot' version '2.3.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'com.mgd.core.gradle.s3' version '1.1.0'
}
.
.
.
s3 {
	bucket = 'mybucketname'
	profile = 'myprofile'
}

task upload(type: S3Upload) {
	key = 'myobjectname'
	file = 'myfileIwantToUpload'
}
```

But I get the error: 
```
A problem occurred evaluating root project 'redacted'.
> Could not get unknown property 'S3Upload' for root project...
```

Must be doing something wrong, any ideas?

Thanks

**Comment by stewartbryson** [comment]
> Hi,
> I have followed the README to add the plugin.
> 
> ```groovy
> plugins {
> 	id "java"
> 	id "maven"
> 	id "maven-publish"
> 	id 'org.springframework.boot' version '2.3.1.RELEASE'
> 	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
> 	id 'com.mgd.core.gradle.s3' version '1.1.0'
> }
> .
> .
> .
> s3 {
> 	bucket = 'mybucketname'
> 	profile = 'myprofile'
> }
> 
> task upload(type: S3Upload) {
> 	key = 'myobjectname'
> 	file = 'myfileIwantToUpload'
> }
> ```
> 
> But I get the error:
> 
> ```
> A problem occurred evaluating root project 'redacted'.
> > Could not get unknown property 'S3Upload' for root project...
> ```
> 
> Must be doing something wrong, any ideas?
> 
> Thanks

Same issue. Did you resolve this? Maybe we also have to apply a dependency, which really shouldn't happen with plugins.

**Comment by peter-thomas-mgd** [comment]
The plugin assumes that you have a reference to the AWS S3 library on your classpath. The plugin does not provide this library.

**Comment by swapnil-kotwal-sp** [comment]
Hi @peter-thomas-mgd I'm using `id 'com.mgd.core.gradle.s3' version '1.3.0'` plugin and still getting error as `Could not get unknown property 'S3Download'`

**Comment by peter-thomas-mgd** [comment]
Does your build file have `import com.mgd.core.gradle.*` at the start of the file?
