### ISSUE TITLE
Use Alternative AWS providers

### ISSUE THREAD

**Issue by sanmibuh** [mygrocerydeals/gradle-s3-plugin#12]
Hello,
It could be helpful allowing to use AWS compatible third-party clouds like Cloudflare, localstack

To do this, simply we need to add another parameter with the service endpoint URL.
Mainly is adding this line

builder.withEndpointConfiguration(new EndpointConfiguration("myAlternativeEndpoint", region))
here:
https://github.com/mygrocerydeals/gradle-s3-plugin/blob/master/src/main/groovy/com/mgd/core/gradle/AbstractS3Task.groovy#L59

What do you think?

I could create a PR with the changes

**Comment by peter-thomas-mgd** [comment]
@sanmibuh thanks for the feedback. I think this is a really interesting idea and think it would add additional value to the plugin feature set. Please submit a pull request with the changes and I can work with you to get into the next release.

**Comment by sanmibuh** [comment]
Done. Could you review it?
I see that the test are using a real ping to the S3? 
I do not test the change of the endpoint because it will fail. To check that we need to run a localstack docker on test containers for example.

**Comment by peter-thomas-mgd** [comment]
This feature has been released in version `1.4.0`.
