### ISSUE TITLE
AWS has changed their system property names

### ISSUE THREAD

**Issue by matthewvon** [mygrocerydeals/gradle-s3-plugin#15]
I suggest updating your README.md.  The old AWS api (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) used aws.accessKeyId and aws.secretKey.  The new "v2" api (https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html) uses aws.accessKeyId and aws.secretAccessKey.  Notice the change in the second property.

**Comment by peter-thomas-mgd** [comment]
@matthewvon Thanks for noticing this. The original example was authored back when the code base was still using v1 of the AWS SDK. It has been fixed in version 2.0.2 of the plugin.
