### ISSUE TITLE
Not able to upload directory to bucket's root

### ISSUE THREAD

**Issue by mhuebner** [mygrocerydeals/gradle-s3-plugin#5]
Currently it is not possible to upload a directory to the root of a bucket:

```
task deployDocs(type: S3Upload) {
    bucket = System.getenv("MY_BUCKET")
    sourceDir = 'site'
}
```

Class `S3Upload` does not support this operation because of groovy truth (keyPrefix is null in the above example):

```
if (keyPrefix && sourceDir) {
```

Would be very nice to have this supported in a next version. 
Any chance to get this quickly released?

**Comment by peter-thomas-mgd** [comment]
This capability has been added to version 1.2.0. `keyPrefix` is optional for both directory upload and download actions.

**Comment by mhuebner** [comment]
Great to hear. Thanks for your work!
